# vim: ft=ruby

brew "autojump"
brew "bat"
brew "curl"
brew "diff-so-fancy"
brew "fish"
brew "fzf"
brew "git"
brew "htop"
brew "jq"
brew "lazygit"
brew "lua-language-server"
brew "mise"
brew "neovim"
brew "openssl"
brew "ripgrep"
brew "starship"
brew "reattach-to-user-namespace"
brew "shellcheck"
brew "tmux"
brew "wifi-password"

tap "universal-ctags/universal-ctags"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]

cask "1password-cli"
cask "dash"
cask "docker"
cask "ghostty"
cask "gpg-suite"
cask "iterm2"
cask "raycast"
cask "spotify"
