# vi: ft=toml
[tools]
dotnet = "latest"
go = "latest"
lua = "latest"
node = "lts"
python = "latest"
ruby = "latest"
rust = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:markdown-toc" = "latest"
golangci-lint = "v2.11.4"
