# vim: ft=ruby

tap "universal-ctags/universal-ctags"

brew "autojump"
brew "bat"
brew "curl"
brew "diff-so-fancy"
brew "htop"
brew "fish"
brew "fzf"
brew "gcc"
brew "git"
brew "openssl"
brew "jq"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
