#!/bin/sh
#
# Run all installers and symlink dotfiles

set -e

echo "Bootstrapping"

echo "Updating submodules"
git submodule init && git submodule update

script/platform
script/symlinks
script/generic
