#!/bin/sh

set -e

# TODO: there are some dependencies and this alphabetical approach leads to errors
# find generic installers and run them interactively
echo "Running generic installers"
find . -name all.sh | while read installer ; do sh -c "${installer}" > /dev/null ; done
