#!/usr/bin/env fish

# Set the terminal and Neovim theme
base16-ocean

# Install fisher https://github.com/jorgebucaran/fisher
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher

# Install fisher packages from ~/.config/fish/fish_plugins
fisher update

source ~/.config/fish/config.fish

# Codespaces has a .gitconfig already setup, so just include
# all of our files instead of messing around.
if set -q CODESPACES
	git config --global include.path ~/.config/git/config
end
