export DOTFILES=$HOME/.dotfiles

# Set our Base16 shell
BASE16_SHELL="$DOTFILES/colors/base16-shell/"
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

set out color scheme
base16_ocean

export EDITOR=nvim
export GOPATH=$HOME/src/go
export ZSH=$DOTFILES/zsh

# ###########
# ## Paths ##
# ###########
#
# Add homebrew coreutils to our path since the MacOS ones
# are not as up to date
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH="$PATH:/usr/local/opt/findutils/libexec/gnubin"
export PATH="$PATH:/usr/local/opt/moreutils/libexec/gnubin"

# Load our ~/.dotfiles/bin folder into the path
export PATH="$PATH:$DOTFILES/bin"

# Add local bin folders to our path
export PATH="$PATH:bin"
export PATH="$PATH:/usr/local/sbin"

# Go paths
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:/usr/local/opt/go/libexec/bin"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# Curl
export PATH="/usr/local/opt/curl/bin:$PATH"

###############

# Fix history search in tmux
bindkey '^R' history-incremental-search-backward
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# Load local configurations ie API keys etc
test -e "${HOME}/.localrc" && source "${HOME}/.localrc"

# source every .zsh file in this rep
for config_file ($ZSH/**/*.zsh) source $config_file

# autojump
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# Ruby
# ----
eval "$(rbenv init -)"

# Hub from GitHub
# ---------------
eval "$(hub alias -s)"

# Nodenv
# ------
eval "$(nodenv init -)"

# Setup fzf
# ---------
if [[ ! "$PATH" == */usr/local/opt/fzf/bin* ]]; then
  export PATH="$PATH:/usr/local/opt/fzf/bin"
fi

# Auto-completion
# ---------------
[[ $- == *i* ]] && source "/usr/local/opt/fzf/shell/completion.zsh" 2> /dev/null

# Key bindings
# ------------
source "/usr/local/opt/fzf/shell/key-bindings.zsh"

# Defaults
# --------
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
compinit

# # Always attach to tmux
if which tmux 2>&1 >/dev/null; then
  if [[ ! $TMUX ]]; then
    tmux attach -t hack || tmux new -s hack; exit
  fi
fi

# aliases for GRC from homebrew
source "`brew --prefix`/etc/grc.bashrc"

export VIMCONFIG=$HOME/.config/nvim
export VIMDATA=$HOME/.local/share/nvim
