source ~/.config/nvim/plugins.vim
source ~/.config/nvim/general.vim
source ~/.config/nvim/keybindings.vim
source ~/.config/nvim/custom_functions.vim
source ~/.config/nvim/file_types.vim
source ~/.config/nvim/markdown.vim
source ~/.config/nvim/plugin_settings.vim
source ~/.config/nvim/format.vim
source ~/.config/nvim/git-commit-editor.vim
